### PR TITLE
Adding MethylationCNVAnalysis to the list

### PR DESCRIPTION
**Pull request by edjuaro**
@bahill , @liefeld , or @tmtabor  could someone accept this pull request to add MethylationCNVAnalysis to the list of nightly tests.

### CODE REVIEW

**Review by bahill — CHANGES_REQUESTED** [review]
You also need a Test target - see ABasicModule for an example.
Also - we should be in the habit of always committing to develop, then merging to master. That allows you or someone else to test your changes before adding them to the canonical nightly tests.

**Comment by edjuaro** [comment]
@bahill added MethylationCNVAnalysis's target and added that test to the nightly tests.

I don't have write permissions to this repo, that's why the only thing I could do is to issue a PR from a branch in my own repo -- this is how I had done it in the past so I figured we wanted to keep writing permissions for just some team members.

This is what GitHub tells me when I want to edit develop:

> You’re editing a file in a project you don’t have write access to. Submitting a change to this file will write it to a new branch in your fork edjuaro/GpUnit, so you can send a pull request.

**Comment by bahill** [comment]
oh - that was not our intent - I think that was a vestige of this being a Broad org, but I think we can add you as a collaborator however we want now? I'll have to investigate.

**Review by bahill — APPROVED** [review]
Looks good

**Pull request merged**
